version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - xioma-automotive-network
    volumes:
      - xioma-automotive-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "27020:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL_ROOT}
      ME_CONFIG_BASICAUTH: false
    networks:
      - xioma-automotive-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - TASK_SERVICE_URL=${TASK_SERVICE_URL}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    depends_on:
      - mongo
    networks:
      - xioma-automotive-network

  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - api-gateway
    networks:
      - xioma-automotive-network

  task-service:
    build: ./task-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGODB_URL}
    depends_on:
      - mongo
      - api-gateway
    networks:
      - xioma-automotive-network

  xioma-auto-client:
    build: ./xioma-auto-client
    ports:
      - "80:80"
    depends_on:
      - mongo
      - api-gateway
    networks:
      - xioma-automotive-network
networks:
  xioma-automotive-network:
    driver: bridge
#    external: true
volumes:
  xioma-automotive-data:
    driver: local
